title = 'Simple configuration'

[[sources]]  # element 0 of an array of sources
position = [1.0, 2.0, 0.0]

# [[sources]]  # element 1 of an array of sources
# position = [10.0, -1.0, 0.0]

# [[sources]]  # element 2 of an array of sources
# ...


[[receivers]]  # element 0 of an array of receivers
position = [11.0, 1.0, 3.0]

# [[receivers]]  # element 1 of an array of receivers
# position = [1.0, 2.0, 3.0]

[geometry]
room = 'data/rooms/simple/walls_room.dae'
# room = 'data/rooms/simple/monkey.dae'
# room = 'data/rooms/simple/long_tube.dae'
# room = 'data/rooms/simple/cena11_rot.dae'
# room = 'data/rooms/simple/simple.dae'
bbox = 'data/rooms/simple/bbox.dae'

