title = 'Simple configuration'

##################### algorithm controls ######################################
[controls]
freq = [63.0, 125.0, 250.0, 500.0, 1000.0, 2000.0, 4000.0, 8000.0]
Nrays = 100                 # Number of rays
ht_length = 3.0             # Length of the impulse response
Dt = 0.001                  # Histogram time resolution
allow_scattering = 0        # Allow scattering or not
transition_order = 2        # Transition order
rec_radius_init = 0.1       # Initial receiver radius
alow_growth = 1             # Allow receiver growth or not
rec_radius_final = 0.5      # Final receiver radius

################### Air properties ############################
[air]
Temperature = 20.0          # Temperature in C
hr = 50.0                   # Relative humidity %
p_atm = 101325.0            # Atmosferic air pressure Pa


################################################################
[[sources]]  # element 0 of an array of sources
position = [3.0, 2.333, 1.2]
orientation = [1.0, 0.0, 0.0]
power_dB = [80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0]
eq_dB = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
delay = 0.0 # delay in [ms]

#[[sources]]  # element 1 of an array of sources
#position = [10.0, -1.0, 1.0]
#orientation = [1.0, 0.0, 0.0]
#power_dB = [80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0]
#eq_dB = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#delay = 0.0 # delay in [ms]

# [[sources]]  # element 2 of an array of sources
# ...

##################################################################
[[receivers]]  # element 0 of an array of receivers
position = [11.0, 1.0, 1.2]
orientation = [1.0, 0.0, 0.0]

[[receivers]]  # element 1 of an array of receivers
position = [1.0, 2.0, 3.0]
orientation = [1.0, 0.0, 0.0]

###################### Geometry #################################
[geometry]
#room = 'data/rooms/simple/walls_room.dae'
# room = 'data/rooms/simple/monkey.dae'
# room = 'data/rooms/simple/long_tube.dae'
#room = 'data/rooms/simple/cena11_rot.dae'
#room = 'data/rooms/simple/simple.dae'
#room = 'data/rooms/simple/example_odeon.dae'
#room = 'data/rooms/simple/masp_cavaletes.dae'
#room = 'data/rooms/simple/MASP_cavaletes_teto.dae'
#room = 'data/rooms/simple/MASP_sem_cavaletes.dae'

room = 'data/legacy/ODEON_Ex_geometry.mat'
#room = 'data/legacy/BostonSH_geometry.mat'
#room = 'data/legacy/Elmia_geometry.mat'
#room = 'data/legacy/studioPTB_ph1.mat'
#room = 'data/legacy/studioPTB_ph2_courtain_closed.mat'
#room = 'data/legacy/studioPTB_ph2_courtain_open.mat'
#bbox = 'data/rooms/simple/bbox.dae'

################### Material database ##########################
[material]
mat_database = 'data/material/DataBase_Odeon.mat'